# Generated by Django 5.1.6 on 2025-03-04 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='タイトル')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('due_Date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('frequency', models.CharField(choices=[('D', '日'), ('W', '週'), ('M', '月')], default='D', max_length=1, verbose_name='頻度')),
                ('repeat', models.CharField(choices=[('none', 'なし'), ('daily', '毎日'), ('weekly', '毎週'), ('monthly', '毎月')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
                'db_table': 'task',
            },
        ),
    ]
